# This workflow will build user-service
name: Build, Push Image and Trigger Deplyment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user-service
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build user-service
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image (tag = SHA)
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_REPO=${{ secrets.DOCKERHUB_USERNAME }}/user-service" >> $GITHUB_ENV

      - name: Checkout ibank-minikube-gitops repo
        uses: actions/checkout@v4
        with:
          repository: techxus/ibank-minikube-gitops
          token: ${{ secrets.GITOPS_REPO_PAT }}
          path: gitops

      - name: Update env/dev values in GitOps repo
        run: |
          FILE="gitops/env/local/user-service-values.yaml"
          mkdir -p "$(dirname "$FILE")"
          cat > "$FILE" <<EOF
          image:
            repository: ${IMAGE_REPO}
            tag: "${IMAGE_TAG}"
          EOF
